### ISSUE TITLE
Audio Icon Reversed

### ISSUE THREAD

**Issue by cgeroux** [katescarth/literary-halifax-mobile-app#11]
I would expect the audio icon on a landmark description page to have the line through it when not playing, and to not have a line through it when playing.

**Comment by David-Owen-Walker** [comment]
This is a subject of [some](http://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan) [debate](http://ux.stackexchange.com/questions/23906/what-toggle-button-should-represent-state-or-action), but fixed in https://github.com/katescarth/literary-halifax-mobile-app/commit/1b470b87e1cb0ba1cf0dde5444dfef94b8f89a64
